# Generated by Django 3.2 on 2021-06-07 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='completetask',
            new_name='complete',
        ),
    ]
