# Generated by Django 3.2 on 2021-06-11 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_createuserform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
    ]
