# Generated by Django 3.2 on 2021-06-11 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0012_task_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='todolist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='CreateUserForm',
        ),
    ]
