# Generated by Django 3.2 on 2021-06-14 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_auto_20210612_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='tasktype',
            field=models.CharField(choices=[('-------', '-------'), ('GROCERY', 'GROCERY'), ('MOVIE', 'MOVIE'), ('HOUSEHOLD', 'HOUSEHOLD'), ('HEALTH', 'HEALTH'), ('SOCIAL', 'SOCIAL'), ('OTHERS', 'OTHERS')], default='-------', max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(default='SOME STRING', max_length=200, unique=True),
        ),
    ]
